<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ling Chen, Hang Zhao, Jiahang Li">
<meta name="dcterms.date" content="2024-01-15">

<title>Hang Zhao Personal Website - MUSA500 Homework 3: The Application of Logistic Regression to Examine the Predictors of Car Crashes Caused by Alcohol</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../MUSA500_Stats/MUSA500_HW1_PredictHouseValues.html">MUSA500_Stats</a></li><li class="breadcrumb-item"><a href="../MUSA500_Stats/MUSA500_HW3.html">MUSA500 Homework 3: The Application of Logistic Regression to Examine the Predictors of Car Crashes Caused by Alcohol</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/Penn_Logo.jpg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="../hangzh@sas.upenn.edu" rel="" title="Email" class="quarto-navigation-tool px-1" aria-label="Email"><i class="bi bi-globe"></i></a>
    <a href="https://github.com/Cyanhang" rel="" title="Hang's GitHub" class="quarto-navigation-tool px-1" aria-label="Hang's GitHub"><i class="bi bi-github"></i></a>
    <a href="../www.linkedin.com/in/hang-zhao-62060a1a9" rel="" title="Hang's Linkedin" class="quarto-navigation-tool px-1" aria-label="Hang's Linkedin"><i class="bi bi-linkedin"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About me</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../analysis/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analysis/1-python-code-blocks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Python code blocks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analysis/2-static-images.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Showing static visualizations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analysis/3-altair-hvplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Altair and Hvplot Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analysis/4-folium.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactive Maps with Folium</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">MUSA500_Stats</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MUSA500_Stats/MUSA500_HW1_PredictHouseValues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MUSA500 Homework 1: Using OLS Regression to Predict Median House Values in Philadelphia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MUSA500_Stats/MUSA500_HW2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MUSA500 Homework 2: Using Spatial Lag, Spatial Error and Geographically Weighted Regression to Predict Median House Values in Philadelphia Block Groups</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MUSA500_Stats/MUSA500_HW3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">MUSA500 Homework 3: The Application of Logistic Regression to Examine the Predictors of Car Crashes Caused by Alcohol</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><strong>Introduction</strong></a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><strong>Methodology</strong></a>
  <ul class="collapse">
  <li><a href="#why-not-ols-regression-for-dv-is-binary" id="toc-why-not-ols-regression-for-dv-is-binary" class="nav-link" data-scroll-target="#why-not-ols-regression-for-dv-is-binary">Why not OLS Regression for DV is binary?</a></li>
  <li><a href="#logistic-regression-overview" id="toc-logistic-regression-overview" class="nav-link" data-scroll-target="#logistic-regression-overview">Logistic Regression: Overview</a>
  <ul class="collapse">
  <li><a href="#the-logit-function" id="toc-the-logit-function" class="nav-link" data-scroll-target="#the-logit-function">The Logit Function</a></li>
  <li><a href="#regression-equation-for-logit-model" id="toc-regression-equation-for-logit-model" class="nav-link" data-scroll-target="#regression-equation-for-logit-model">Regression Equation for Logit Model</a></li>
  </ul></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#quality-of-model-fit" id="toc-quality-of-model-fit" class="nav-link" data-scroll-target="#quality-of-model-fit">Quality of Model Fit</a></li>
  <li><a href="#assumptions-of-logistic-regression" id="toc-assumptions-of-logistic-regression" class="nav-link" data-scroll-target="#assumptions-of-logistic-regression">Assumptions of Logistic Regression</a></li>
  <li><a href="#exploratory-analysis-before-logistic-regression" id="toc-exploratory-analysis-before-logistic-regression" class="nav-link" data-scroll-target="#exploratory-analysis-before-logistic-regression">Exploratory Analysis Before Logistic Regression</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><strong>Results</strong></a>
  <ul class="collapse">
  <li><a href="#exploratory-analysis" id="toc-exploratory-analysis" class="nav-link" data-scroll-target="#exploratory-analysis">Exploratory analysis</a>
  <ul class="collapse">
  <li><a href="#tabulation-of-the-dependent-variable-predictors" id="toc-tabulation-of-the-dependent-variable-predictors" class="nav-link" data-scroll-target="#tabulation-of-the-dependent-variable-predictors">Tabulation of the Dependent Variable &amp; Predictors</a></li>
  <li><a href="#association" id="toc-association" class="nav-link" data-scroll-target="#association">Association</a></li>
  </ul></li>
  <li><a href="#logistic-regression-assumptions" id="toc-logistic-regression-assumptions" class="nav-link" data-scroll-target="#logistic-regression-assumptions">Logistic Regression Assumptions</a>
  <ul class="collapse">
  <li><a href="#pairwise-pearson-correlations-matrix" id="toc-pairwise-pearson-correlations-matrix" class="nav-link" data-scroll-target="#pairwise-pearson-correlations-matrix">Pairwise Pearson Correlations Matrix</a></li>
  <li><a href="#assumptions-check" id="toc-assumptions-check" class="nav-link" data-scroll-target="#assumptions-check">Assumptions Check</a></li>
  </ul></li>
  <li><a href="#logistic-regression-results" id="toc-logistic-regression-results" class="nav-link" data-scroll-target="#logistic-regression-results">Logistic Regression Results</a>
  <ul class="collapse">
  <li><a href="#logistic-regression-with-all-predictors" id="toc-logistic-regression-with-all-predictors" class="nav-link" data-scroll-target="#logistic-regression-with-all-predictors">Logistic Regression With All Predictors</a></li>
  <li><a href="#roc" id="toc-roc" class="nav-link" data-scroll-target="#roc">ROC</a></li>
  <li><a href="#logistic-regression-with-binary-predictors-only" id="toc-logistic-regression-with-binary-predictors-only" class="nav-link" data-scroll-target="#logistic-regression-with-binary-predictors-only">Logistic Regression With Binary Predictors Only</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#summarizing-findings" id="toc-summarizing-findings" class="nav-link" data-scroll-target="#summarizing-findings">Summarizing findings</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  </ul></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/Cyanhang/Hang/blob/main/MUSA500_Stats/MUSA500_HW3.Rmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MUSA500 Homework 3: The Application of Logistic Regression to Examine the Predictors of Car Crashes Caused by Alcohol</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ling Chen, Hang Zhao, Jiahang Li </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 15, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div style="page-break-after: always;"></div>
<section id="introduction" class="level1">
<h1><strong>Introduction</strong></h1>
<p>Traffic safety is a critical global concern, with vehicular fatalities being a particularly prominent issue. Driving under the influence of alcohol is exceedingly hazardous and poses a significant threat to public safety. In the US itself, according to the United States Department of Transportation, approximately 31% of all traffic-related fatalities in the US are attributed to incidents involving drivers under the influence of alcohol. Every day in the United States, 32 individuals lose their lives in accidents that involve an alcohol-impaired driver, equating to a fatality approximately every 45 minutes (NHTSA, 2020). Philadelphia, renowned as one of the United States’ most historic cities and the most populous county in Pennsylvania, is characterized by traffic systems that are significantly outdated and complex. These conditions amplify the potential for vehicular accidents within the city. In response, Philadelphia has initiated the ambitious Vision Zero initiative, which aimed to eliminate all traffic-related fatalities and severe injuries on its streets by 2030 (City of Philadelphia, 2023). This proactive approach underscores the city’s commitment to enhancing road safety and protecting its citizens.</p>
<p>In this report, we will analyze a dataset containing 43,364 vehicular crashes that occurred within the residential block groups of Philadelphia from 2008 to 2012. Our objective is to discern the predictors of accidents involving drunk driving. The dependent variable DRINKING_D is a binary indicator of the presence of a drinking driver, where 1 means ‘Yes’ and 0 means ‘No’. Our predictor variables are a blend of binary and continuous types, including crash resulted in fatality or major injury, crash involved an overturned vehicle, drivers was using cell phone, crash involved speeding car, crash involved aggressive driving, crash involved at least one driver who was 16 or 17 years old, crash involved at least one driver who was at least 65 years old, percentage of individuals 25 years of age or older who have at least a bachelor’s degree in the census block group where the crash took place, and the median household income in that census block group. By examining these predictors in relation to the DRINKING_D variable using logistic regression analysis in R, the analysis aims to identify patterns and factors that contribute to the risk of alcohol-impaired driving in Philadelphia’s residential areas. The findings could provide valuable insights for targeted prevention strategies and policy interventions to reduce drunk-driving incidents.</p>
</section>
<section id="methodology" class="level1">
<h1><strong>Methodology</strong></h1>
<section id="why-not-ols-regression-for-dv-is-binary" class="level2">
<h2 class="anchored" data-anchor-id="why-not-ols-regression-for-dv-is-binary">Why not OLS Regression for DV is binary?</h2>
<p>Previously, we have performed Ordinary Least Squares (OLS) regression for continuous dependent variables, where the beta coefficients represent the amount of changes in the dependent variable Y corresponding to a one-unit increase in predictor X. However, in the current context, the dependent variable is binary, taking on values of either 0 or 1. Consequently, a one-unit increase in X does not translate to a proportional change in Y, since Y can only switch between the binary states of 0 and 1. Therefore, the concept of a beta coefficient increase in Y as used in OLS is inapplicable here.</p>
</section>
<section id="logistic-regression-overview" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-overview">Logistic Regression: Overview</h2>
<section id="the-logit-function" class="level3">
<h3 class="anchored" data-anchor-id="the-logit-function">The Logit Function</h3>
<p>Instead, predicting P(Y=1|X=x), the probability that Y=1 could be an alternative, with a translator function such that the closer the predicted y value from linear regression model is to negative infinite, the closer our predicted probability is to 0, and the closer the y predicted value is to positive infinite, the closer predicted probability is to 1, with no predicted probabilities are less than 0 or greater than 1. This translator function here we are going to use is the Logit Function, which has an equation looks like this for one predictor:</p>
<p><span class="math display">\[
\ln\left(\frac{p}{1 - p}\right) = \beta_0 + \beta_1 x_1 + \varepsilon
\]</span> Where p = P(Y=1), and the quantity ‘p/(1-p)’ is called the odds, and the quantity ln(p/(1-p)) is called the log odds, or logit. In another words, the odds may be calculated as the desirable outcomes divided by the undesirable outcomes, showing as follows: <span class="math display">\[
Odds = \frac{\#\ \text{desirable outcomes}}{\#\ \text{undesirable outcomes}}
\]</span></p>
<p>Logistic function, or the inverse-logit function, is another form of logit function, which can be expressed as: <span class="math display">\[
p = \frac{e^{\beta_{0} + \beta_{1} x_{1}}}{1 + e^{\beta_{0} + \beta_{1} x_{1}}} = \frac{1}{1 + e^{-\left(\beta_{0} + \beta_{1} x_{1}\right)}}
\]</span> Express the logistic function in the form of line graph, it looks like a ‘S’ shape, which is plotted below:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="MUSA500_HW3_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the graph we can see that when <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span>X1 equals to zero, the probability of Y=1 is 50%; As <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span>X1 becomes larger, p approaches to 1; As <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span>X1 becomes smaller, p approaches to 0.</p>
</section>
<section id="regression-equation-for-logit-model" class="level3">
<h3 class="anchored" data-anchor-id="regression-equation-for-logit-model">Regression Equation for Logit Model</h3>
<p>Our car crash data set has 43,364 observations. The relevant variables are described below:</p>
<ul>
<li>Dependent Variable: <code>DRINKING_D</code>, Drinking driver indicator (1 = Yes, 0 = No)</li>
<li>Predictor: <code>FATAL_OR_M</code>, Crash resulted in fatality or major injury (1 = Yes, 0 = No)</li>
<li>Predictor: <code>OVERTURNED</code>, Crash involved an overturned vehicle (1 = Yes, 0 = No)</li>
<li>Predictor: <code>CELL_PHONE</code>, Driver was using cell phone (1= Yes, 0 = No)</li>
<li>Predictor: <code>SPEEDING</code>, Crash involved speeding car (1 = Yes, 0 = No)</li>
<li>Predictor: <code>AGGRESSIVE</code>, Crash involved aggressive driving (1 = Yes, 0 = No)</li>
<li>Predictor: <code>DRIVER1617</code>, Crash involved at least one driver who was 16 or 17 years old (1 = Yes, 0 = No)</li>
<li>Predictor: <code>DRIVER65PLUS</code>, Crash involved at least one driver who was at least 65 years old (1 = Yes, 0 = No)</li>
<li>Predictor: <code>PCTBACHMOR</code>,% of individuals 25 years of age or older who have at least a bachelor’s degree in the Census Block Group where the crash took place</li>
<li>Predictor: <code>MEDHHINC</code>, Median household income in the Census Block Group where the crash took place</li>
</ul>
<p>The logit function of the regression model, which incorporates multiple predictors (our model includes nine predictors, of which seven are binary and two are continuous), can be articulated as follows:</p>
<p><span class="math display">\[
\begin{aligned}
ODDS(DRINKING\_D=1) = \beta_0 + \beta_1FATAL\_OR\_M + \beta_2OVERTURNED + \beta_3CELL\_PHONE \\
+ \beta_4SPEEDING + \beta_5AGGRESSIVE + \beta_6DRIVER1617
+ \beta_7DRIVER65PLUS + \beta_8PCTBACHMOR \\
+ \beta_9 MEDHHINC + \varepsilon
\end{aligned}
\]</span></p>
<p>The equation represents the log odds of the event where Y equals 1, corresponding to the dependent variable DRINKING_D being 1. This indicates the scenario where a drinking driver is involved. It’s calculated as the ratio of the probability of DRINKING_D equals to 1 (presence of a drinking driver) to the probability of DRINKING_D does not equals to 1 (absence of a drinking driver).</p>
<p>When Beta coefficient is positive, it indicates that as the predictor variable increases, the log odds of the outcome occurring increases, meaning the outcome becomes more likely, when beta coefficient is negative, the log odds of the outcome occurring decreases when predictor variable increases, and the outcome becomes less likely.</p>
<p>Solving the equation of logit function to make p=P(Y=1), we can get a function generally known as the inverse logit, or the logistic function, in which it has the equation like this:</p>
<p><span class="math display">\[
p = \frac{e^{\beta_0 + \beta_1 x_1}}{1 + e^{\beta_0 + \beta_1 x_1}} = \frac{1}{1 + e^{-(\beta_0 + \beta_1 x_1)}}
\]</span></p>
<p>Plugging in the variables that we are interested in, in this case are the car crash model variables:</p>
<p><span class="math display">\[
\begin{aligned}
p &amp;= P(DRINKING\_D=1) \\
  &amp;= \frac{1}{1 + e^{-(\beta_0 + \beta_1FATAL\_OR\_M + \beta_2 OVERTURNED + \ldots + \beta_9 MEDHHINC)}} \\
  &amp;= \frac{1}{1 + e^{-\left(\beta_0 + \sum_{i=1}^{9} \beta_{i} \times X_{i}\right)}}
\end{aligned}
\]</span></p>
</section>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<p>In executing the logistic regression, our initial step involves testing the null hypothesis (H0), which considers that <span class="math inline">\(\beta_i\)</span> = 0. This implies that the ith independent variable has no impact on the log-odds of the outcome. We contrast this with the alternative hypothesis (Ha), which asserts that <span class="math inline">\(\beta_i\)</span> <span class="math inline">\(\neq\)</span> 0, suggesting that the independent variable in question does indeed affect the log-odds of the outcome. This framework is crucial for determining the significance of each predictor in the model. Then, we will look at the quantity, which is sometimes called the Wald statistic within the context of logistic regression, to examine the hypothesis test. The Wald statistic follows a standard normal distribution under the null hypothesis. Thus, the quantity of the Wald statistics is equivalent to a z-score in a standard normal distribution. Then, we can find the p-value associated with the Wald statistics referencing the standard normal (z) distribution tables. If the Wald statistic is far from zero, which corresponds to a small p-value in the standard normal (z) distribution tables, we can reject the null hypothesis and get the conclusion that the independent variable has a significant effect on the outcome.</p>
<p>At the same time, in the context of logistic regression, while the estimated <span class="math inline">\(\beta\)</span> coefficients provide valuable information about the direction and magnitude of the effect a predictor variable has on the log-odds of the outcome, many statisticians and researchers also interpret the results based on odds ratios. The reason is that odds ratios offer a clear and interpretable measure of the strength and direction of the association between the predictor variables and the binary outcome. An odds ratio (OR) is the exponentiated form of the logistic regression coefficient. This transformation is particularly useful because it translates the coefficients into a multiplicative effect on the odds of the outcome occurring for a one-unit increase in the predictor variable. When the odds ratio is: Greater than 1, it indicates that as the predictor increases by one unit, the odds of the outcome occurring increase. Less than 1, it indicates that as the predictor increases by one unit, the odds of the outcome occurring decrease. Exactly 1, it indicates that as the predictor has no effect on the odds of the outcome occurring.</p>
</section>
<section id="quality-of-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="quality-of-model-fit">Quality of Model Fit</h2>
<p>Unlike OLS regression, R-Squared can’t be interpreted in logistic regression as the % of variance explained by the model. As there is no continuous outcome variable to explain variance for. Instead, it models the probability of an event occurring based on other independent variables.</p>
<p>Akaike Information Criterion (AIC) is a measure of the goodness of fit of an estimated statistical model. It’s a relative measure of the information that is lost when a given model is used to describe reality and can be said to describe the tradeoff between precision and complexity of the model. Typically, the lower AIC, the better the fit.</p>
<p>Sensitivity (True Positive Rate) measures the proportion of actual positives which are correctly identified as such and is complementary to the False Negative Rate. Specificity (Ture Negative Rate) measures the proportion of negatives which are correctly identified as such and is complementary to the False Positive Rate. Misclassification rate refers to both False Negative Rate and False Positive Rate. Technically, we’re looking for more correct predictions, for example, being able to predict a high probability of Y=1 if Y is actually 1, and a low probability of Y=1 if Y is actually 0. That’s being said, higher values of sensitivity and specificity are better. The fitted values 𝑦̂, which refer to probabilities that Y=1.</p>
<p><span class="math display">\[
P(Y = 1) = \hat{y}_i = \frac{e^{\hat{\beta}_0 + \hat{\beta}_1 x_{1i} + \ldots + \hat{\beta}_3 x_{3i}}}{1 + e^{\hat{\beta}_0 + \hat{\beta}_1 x_{1i} + \ldots + \hat{\beta}_3 x_{3i}}}
\]</span></p>
<p>And similarly, <span class="math display">\[
\epsilon = y_i - \hat{y}_i
\]</span></p>
<p>The choice of cut-off value demonstrates the trade-offs between different specificity and sensitivity and really depends on different scenarios. Using a cut-off of 0.5 may not be suitable for imbalanced datasets. Ideally, we should choose a cut-off value that will somehow balance and optimize the sensitivity and specificity.</p>
<p>ROC curve is a way to plot sensitivity (True Positive Rate) against Specificity (False Positive Rate), it can be used to examine predictive quality of the model and determine a best cut-off value by optimizing sensitivity and specificity. When interpreting the ROC Curve plot, a cut-off for which the ROC curve has the minimum distance from the upper left corner of the graph maximizes sensitivity and specificity. We can also look at the Youden index, a cut-off for which sensitivity and specificity is maximized. For area under ROC Curve(AUC), it is a measure of prediction accuracy of the model. Usually, higher AUCs mean that we can find a cut-off value for which both sensitivity and specificity of the model are relatively high. The possible values range between 0.5 and 1, a rough guide for classifying the accuracy is: * .90-1 = excellent; * .80-.90 = good; * .70-.80 = fair; * .60-.70 = poor; * .50-.60 = fail; AUC may be interpreted as the probability that the model correctly ranks two randomly selected observations where one has Y=1 and the other one has Y=0.</p>
</section>
<section id="assumptions-of-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-of-logistic-regression">Assumptions of Logistic Regression</h2>
<p>With OLS regression, we need to make sure the linear relationship between dependent variable and each predictor, the normality of residuals, and homoscedasticity. But in Logistic regression, there’re no such assumptions. However, the dependent variable in logistic regression must be binary. Also, there should be independence of observations and no severe multicollinearity. Besides that, larger samples are also needed than for OLS because Maximum Likelihood Estimation is used to estimate regression coefficients. For example, at least 50 observations per predictor are needed, compared to about 10 pre predictor in OLS regression.</p>
</section>
<section id="exploratory-analysis-before-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis-before-logistic-regression">Exploratory Analysis Before Logistic Regression</h2>
<p>Prior to executing logistic regression, we will conduct exploratory analyses to gain a thorough understanding of the dataset and the interrelations among variables. Initially, we will go through the process of cross-tabulations. This technique examines the connections between the dependent binary variable and other binary predictors. Utilizing R, we’ll construct contingency tables to display the variables’ frequency distributions. Additionally, we will apply the Chi-Square (<span class="math inline">\(\chi^2\)</span>) test in R to determine if the distribution of one categorical variable depends on another. For example, a cross-tabulation of the DRINKING_D and FATAL_OR_M variables will test the Null Hypothesis (H0): There is no discrepancy in fatality rates between crashes with alcohol-impaired drivers and those without. Conversely, the Alternative Hypothesis (Ha) states that such a discrepancy exists. A significant <span class="math inline">\(\chi^2\)</span> statistic, combined with a p-value under 0.05, would suggest enough evidence to reject the null hypothesis. In other words, we can conclude there is a significant association between alcohol impairment in drivers and the likelihood of crash fatalities.</p>
<p>Further, we will conduct an independent samples t-test to compare the means of a continuous variable across two distinct groups. This test is designed to discern whether any observed mean differences are random or indicative of a genuine disparity in the population. For instance, using PCTBACHMOR as an example, the test will find out if there is a statistically significant mean difference in PCTBACHMOR between crashes with and without alcohol-impaired drivers. Here, the null hypothesis (H0) states that there is no mean difference in PCTBACHMOR values between the two groups, while the alternative hypothesis (Ha) suggests a disparity. Should the t-statistic be significantly high, and the p-value falls beneath 0.05, we would reject H0, concluding a notable difference in average PCTBACHMOR values between crashes involving alcohol-impaired drivers and those that do not.</p>
</section>
</section>
<section id="results" class="level1">
<h1><strong>Results</strong></h1>
<section id="exploratory-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis">Exploratory analysis</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        CRN DRINKING_D COLLISION_ FATAL_OR_M OVERTURNED CELL_PHONE SPEEDING
1 200806719          0          7          0          0          0        0
2 200807695          0          7          1          0          0        0
3 200808809          0          8          0          0          0        0
4 200809857          0          5          0          0          0        0
5 200812736          0          1          0          0          0        0
6 200907381          1          7          1          0          0        0
  AGGRESSIVE DRIVER1617 DRIVER65PLUS      AREAKEY PCTBACHMOR MEDHHINC
1          0          0            0 421010001001    64.4737    49107
2          1          0            0 421010001001    64.4737    49107
3          0          0            0 421010001001    64.4737    49107
4          1          0            0 421010001001    64.4737    49107
5          0          0            0 421010001001    64.4737    49107
6          0          0            1 421010001001    64.4737    49107</code></pre>
</div>
</div>
<section id="tabulation-of-the-dependent-variable-predictors" class="level3">
<h3 class="anchored" data-anchor-id="tabulation-of-the-dependent-variable-predictors">Tabulation of the Dependent Variable &amp; Predictors</h3>
<p>Let’s look at the tabulation of our binary dependent variable, ‘DRINKING_D’.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      CRN              DRINKING_D        COLLISION_      FATAL_OR_M     
 Min.   :200800863   Min.   :0.00000   Min.   :0.000   Min.   :0.00000  
 1st Qu.:200905452   1st Qu.:0.00000   1st Qu.:2.000   1st Qu.:0.00000  
 Median :201008468   Median :0.00000   Median :4.000   Median :0.00000  
 Mean   :201021771   Mean   :0.05731   Mean   :4.433   Mean   :0.03157  
 3rd Qu.:201111811   3rd Qu.:0.00000   3rd Qu.:7.000   3rd Qu.:0.00000  
 Max.   :201303171   Max.   :1.00000   Max.   :9.000   Max.   :1.00000  
   OVERTURNED        CELL_PHONE         SPEEDING         AGGRESSIVE    
 Min.   :0.00000   Min.   :0.00000   Min.   :0.00000   Min.   :0.0000  
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.0000  
 Median :0.00000   Median :0.00000   Median :0.00000   Median :0.0000  
 Mean   :0.01665   Mean   :0.01047   Mean   :0.03508   Mean   :0.4483  
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:1.0000  
 Max.   :1.00000   Max.   :1.00000   Max.   :1.00000   Max.   :1.0000  
   DRIVER1617       DRIVER65PLUS       AREAKEY               PCTBACHMOR    
 Min.   :0.00000   Min.   :0.0000   Min.   :421010001001   Min.   : 0.000  
 1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:421010104004   1st Qu.: 5.176  
 Median :0.00000   Median :0.0000   Median :421010194001   Median :10.015  
 Mean   :0.01582   Mean   :0.1005   Mean   :421010195889   Mean   :16.572  
 3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:421010292004   3rd Qu.:20.758  
 Max.   :1.00000   Max.   :1.0000   Max.   :421010366001   Max.   :92.987  
    MEDHHINC     
 Min.   :  2499  
 1st Qu.: 21277  
 Median : 29464  
 Mean   : 31513  
 3rd Qu.: 38068  
 Max.   :200001  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
40879  2485 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
        0         1 
0.9426944 0.0573056 </code></pre>
</div>
</div>
<p>We see that there are 94.3% drivers who drink while driving, and only 5.7% who don’t drink. The probability of drivers who drink while driving can be calculated using the formula</p>
<p><span class="math display">\[Probability(DRINKING) = \frac{Number \; of \; Drinking \; Driver}{Total \; Number \; of \; Drivers} = \frac{40879}{43364} = .94. \]</span></p>
<p>Similarly, the odds of drinking drivers can be calculated using the formula</p>
<p><span class="math display">\[Odds(DRINKING) = \frac{Number \; of \; Drinking \; Drivers}{Number \; of \; Non-drinking \; Drivers} = \frac{40879}{2485} = 16.45. \]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
                  | mydata$FATAL_OR_M 
mydata$DRINKING_D |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                0 |     39698 |      1181 |     40879 | 
                  |     0.945 |     0.863 |           | 
------------------|-----------|-----------|-----------|
                1 |      2297 |       188 |      2485 | 
                  |     0.055 |     0.137 |           | 
------------------|-----------|-----------|-----------|
     Column Total |     41995 |      1369 |     43364 | 
                  |     0.968 |     0.032 |           | 
------------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  167.5615     d.f. =  1     p =  0.00000000000000000000000000000000000002522202 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  166.0354     d.f. =  1     p =  0.00000000000000000000000000000000000005434077 

 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
                  | mydata$OVERTURNED 
mydata$DRINKING_D |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                0 |     40267 |       612 |     40879 | 
                  |     0.944 |     0.848 |           | 
------------------|-----------|-----------|-----------|
                1 |      2375 |       110 |      2485 | 
                  |     0.056 |     0.152 |           | 
------------------|-----------|-----------|-----------|
     Column Total |     42642 |       722 |     43364 | 
                  |     0.983 |     0.017 |           | 
------------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  122.788     d.f. =  1     p =  0.0000000000000000000000000001551762 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  121.0052     d.f. =  1     p =  0.000000000000000000000000000381124 

 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
                  | mydata$CELL_PHONE 
mydata$DRINKING_D |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                0 |     40453 |       426 |     40879 | 
                  |     0.943 |     0.938 |           | 
------------------|-----------|-----------|-----------|
                1 |      2457 |        28 |      2485 | 
                  |     0.057 |     0.062 |           | 
------------------|-----------|-----------|-----------|
     Column Total |     42910 |       454 |     43364 | 
                  |     0.990 |     0.010 |           | 
------------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  0.162071     d.f. =  1     p =  0.6872569 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  0.09065262     d.f. =  1     p =  0.7633491 

 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
                  | mydata$SPEEDING 
mydata$DRINKING_D |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                0 |     39618 |      1261 |     40879 | 
                  |     0.947 |     0.829 |           | 
------------------|-----------|-----------|-----------|
                1 |      2225 |       260 |      2485 | 
                  |     0.053 |     0.171 |           | 
------------------|-----------|-----------|-----------|
     Column Total |     41843 |      1521 |     43364 | 
                  |     0.965 |     0.035 |           | 
------------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  376.7808     d.f. =  1     p =  0.000000000000000000000000000000000000000000000000000000000000000000000000000000000006249562 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  374.6039     d.f. =  1     p =  0.00000000000000000000000000000000000000000000000000000000000000000000000000000000001861184 

 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
                  | mydata$AGGRESSIVE 
mydata$DRINKING_D |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                0 |     22357 |     18522 |     40879 | 
                  |     0.934 |     0.953 |           | 
------------------|-----------|-----------|-----------|
                1 |      1569 |       916 |      2485 | 
                  |     0.066 |     0.047 |           | 
------------------|-----------|-----------|-----------|
     Column Total |     23926 |     19438 |     43364 | 
                  |     0.552 |     0.448 |           | 
------------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  67.60186     d.f. =  1     p =  0.000000000000000200079 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  67.2607     d.f. =  1     p =  0.0000000000000002378758 

 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
                  | mydata$DRIVER1617 
mydata$DRINKING_D |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                0 |     40205 |       674 |     40879 | 
                  |     0.942 |     0.983 |           | 
------------------|-----------|-----------|-----------|
                1 |      2473 |        12 |      2485 | 
                  |     0.058 |     0.017 |           | 
------------------|-----------|-----------|-----------|
     Column Total |     42678 |       686 |     43364 | 
                  |     0.984 |     0.016 |           | 
------------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  20.45167     d.f. =  1     p =  0.000006115619 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  19.7097     d.f. =  1     p =  0.000009014275 

 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
                  | mydata$DRIVER65PLUS 
mydata$DRINKING_D |         0 |         1 | Row Total | 
------------------|-----------|-----------|-----------|
                0 |     36642 |      4237 |     40879 | 
                  |     0.939 |     0.973 |           | 
------------------|-----------|-----------|-----------|
                1 |      2366 |       119 |      2485 | 
                  |     0.061 |     0.027 |           | 
------------------|-----------|-----------|-----------|
     Column Total |     39008 |      4356 |     43364 | 
                  |     0.900 |     0.100 |           | 
------------------|-----------|-----------|-----------|

 
Statistics for All Table Factors


Pearson's Chi-squared test 
------------------------------------------------------------
Chi^2 =  80.6047     d.f. =  1     p =  0.000000000000000000275703 

Pearson's Chi-squared test with Yates' continuity correction 
------------------------------------------------------------
Chi^2 =  79.9888     d.f. =  1     p =  0.0000000000000000003765375 

 </code></pre>
</div>
</div>
<p>Prior to the predictive modeling, we use the Chi-Square test to determine whether the distribution of the categorical variable varies with respect to the drunk driving. From the table below, we can see that the majority of the variables except cell phone have a P-value lower than 0.05. Therefore, we can reject the null hypothesis and confirm that there are associations between drunk driving and overturned vehicle, speeding car, aggressive driving,young driver, old drivers, crash fatalities.</p>
<div class="cell">
<div class="cell-output-display">

<div id="lqbjyxrgxi" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#lqbjyxrgxi table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#lqbjyxrgxi thead, #lqbjyxrgxi tbody, #lqbjyxrgxi tfoot, #lqbjyxrgxi tr, #lqbjyxrgxi td, #lqbjyxrgxi th {
  border-style: none;
}

#lqbjyxrgxi p {
  margin: 0;
  padding: 0;
}

#lqbjyxrgxi .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lqbjyxrgxi .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#lqbjyxrgxi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lqbjyxrgxi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lqbjyxrgxi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lqbjyxrgxi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lqbjyxrgxi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lqbjyxrgxi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lqbjyxrgxi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lqbjyxrgxi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lqbjyxrgxi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lqbjyxrgxi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lqbjyxrgxi .gt_spanner_row {
  border-bottom-style: hidden;
}

#lqbjyxrgxi .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#lqbjyxrgxi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lqbjyxrgxi .gt_from_md > :first-child {
  margin-top: 0;
}

#lqbjyxrgxi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lqbjyxrgxi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lqbjyxrgxi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#lqbjyxrgxi .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#lqbjyxrgxi .gt_row_group_first td {
  border-top-width: 2px;
}

#lqbjyxrgxi .gt_row_group_first th {
  border-top-width: 2px;
}

#lqbjyxrgxi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lqbjyxrgxi .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#lqbjyxrgxi .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#lqbjyxrgxi .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lqbjyxrgxi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lqbjyxrgxi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lqbjyxrgxi .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#lqbjyxrgxi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lqbjyxrgxi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lqbjyxrgxi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lqbjyxrgxi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lqbjyxrgxi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lqbjyxrgxi .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lqbjyxrgxi .gt_left {
  text-align: left;
}

#lqbjyxrgxi .gt_center {
  text-align: center;
}

#lqbjyxrgxi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lqbjyxrgxi .gt_font_normal {
  font-weight: normal;
}

#lqbjyxrgxi .gt_font_bold {
  font-weight: bold;
}

#lqbjyxrgxi .gt_font_italic {
  font-style: italic;
}

#lqbjyxrgxi .gt_super {
  font-size: 65%;
}

#lqbjyxrgxi .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#lqbjyxrgxi .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#lqbjyxrgxi .gt_indent_1 {
  text-indent: 5px;
}

#lqbjyxrgxi .gt_indent_2 {
  text-indent: 10px;
}

#lqbjyxrgxi .gt_indent_3 {
  text-indent: 15px;
}

#lqbjyxrgxi .gt_indent_4 {
  text-indent: 20px;
}

#lqbjyxrgxi .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="7" class="gt_heading gt_title gt_font_normal gt_bottom_border" style="">Traffic Accident Statistics - Categorical Variables</td>
    </tr>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Category">Category</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Drinking_N">Drinking_N</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Drinking_Perc">Drinking_Perc</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Non_Drinking_N">Non_Drinking_N</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Non_Drinking_Perc">Non_Drinking_Perc</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Total_N">Total_N</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="p_value">p_value</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Category" class="gt_row gt_left">FATAL_OR_M</td>
<td headers="Drinking_N" class="gt_row gt_right">188</td>
<td headers="Drinking_Perc" class="gt_row gt_right">0.43354</td>
<td headers="Non_Drinking_N" class="gt_row gt_right">1,181</td>
<td headers="Non_Drinking_Perc" class="gt_row gt_right">2.72346</td>
<td headers="Total_N" class="gt_row gt_right">1,369</td>
<td headers="p_value" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Category" class="gt_row gt_left">OVERTURNED</td>
<td headers="Drinking_N" class="gt_row gt_right">110</td>
<td headers="Drinking_Perc" class="gt_row gt_right">0.25367</td>
<td headers="Non_Drinking_N" class="gt_row gt_right">612</td>
<td headers="Non_Drinking_Perc" class="gt_row gt_right">1.41131</td>
<td headers="Total_N" class="gt_row gt_right">722</td>
<td headers="p_value" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Category" class="gt_row gt_left">CELL_PHONE</td>
<td headers="Drinking_N" class="gt_row gt_right">28</td>
<td headers="Drinking_Perc" class="gt_row gt_right">0.06457</td>
<td headers="Non_Drinking_N" class="gt_row gt_right">426</td>
<td headers="Non_Drinking_Perc" class="gt_row gt_right">0.98238</td>
<td headers="Total_N" class="gt_row gt_right">454</td>
<td headers="p_value" class="gt_row gt_right">0.68726</td></tr>
    <tr><td headers="Category" class="gt_row gt_left">SPEEDING</td>
<td headers="Drinking_N" class="gt_row gt_right">260</td>
<td headers="Drinking_Perc" class="gt_row gt_right">0.59958</td>
<td headers="Non_Drinking_N" class="gt_row gt_right">1,261</td>
<td headers="Non_Drinking_Perc" class="gt_row gt_right">2.90794</td>
<td headers="Total_N" class="gt_row gt_right">1,521</td>
<td headers="p_value" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Category" class="gt_row gt_left">AGGRESSIVE</td>
<td headers="Drinking_N" class="gt_row gt_right">916</td>
<td headers="Drinking_Perc" class="gt_row gt_right">2.11235</td>
<td headers="Non_Drinking_N" class="gt_row gt_right">18,522</td>
<td headers="Non_Drinking_Perc" class="gt_row gt_right">42.71285</td>
<td headers="Total_N" class="gt_row gt_right">19,438</td>
<td headers="p_value" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Category" class="gt_row gt_left">DRIVER1617</td>
<td headers="Drinking_N" class="gt_row gt_right">12</td>
<td headers="Drinking_Perc" class="gt_row gt_right">0.02767</td>
<td headers="Non_Drinking_N" class="gt_row gt_right">674</td>
<td headers="Non_Drinking_Perc" class="gt_row gt_right">1.55428</td>
<td headers="Total_N" class="gt_row gt_right">686</td>
<td headers="p_value" class="gt_row gt_right">0.00001</td></tr>
    <tr><td headers="Category" class="gt_row gt_left">DRIVER65PLUS</td>
<td headers="Drinking_N" class="gt_row gt_right">119</td>
<td headers="Drinking_Perc" class="gt_row gt_right">0.27442</td>
<td headers="Non_Drinking_N" class="gt_row gt_right">4,237</td>
<td headers="Non_Drinking_Perc" class="gt_row gt_right">9.77078</td>
<td headers="Total_N" class="gt_row gt_right">4,356</td>
<td headers="p_value" class="gt_row gt_right">0</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  mydata$PCTBACHMOR by mydata$DRINKING_D
t = -0.10842, df = 2777.5, p-value = 0.9137
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.7991398  0.7153982
sample estimates:
mean in group 0 mean in group 1 
       16.56986        16.61173 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  mydata$MEDHHINC by mydata$DRINKING_D
t = -1.4053, df = 2763.9, p-value = 0.16
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -1235.2508   203.8544
sample estimates:
mean in group 0 mean in group 1 
       31483.05        31998.75 </code></pre>
</div>
</div>
<p>For the continuous variables <code>PCTBACHMOR</code>,<code>MEDHHINC</code>, we further examine whether their means differ for drunk driving or non-drunk driving. By using the independent samples t-test, the P-value for both variables are not statistically significantly different for crashes that involve drunk drivers and crashes that don’t. Therefore, it can be concluded that the average values of the variables <code>PCTBACHMOR</code> and <code>MEDHHINC</code> are the same for accidents involving drunk drivers and those not involving them.</p>
<div class="cell">
<div class="cell-output-display">

<div id="keqpffaeoj" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#keqpffaeoj table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#keqpffaeoj thead, #keqpffaeoj tbody, #keqpffaeoj tfoot, #keqpffaeoj tr, #keqpffaeoj td, #keqpffaeoj th {
  border-style: none;
}

#keqpffaeoj p {
  margin: 0;
  padding: 0;
}

#keqpffaeoj .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#keqpffaeoj .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#keqpffaeoj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#keqpffaeoj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#keqpffaeoj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#keqpffaeoj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#keqpffaeoj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#keqpffaeoj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#keqpffaeoj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#keqpffaeoj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#keqpffaeoj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#keqpffaeoj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#keqpffaeoj .gt_spanner_row {
  border-bottom-style: hidden;
}

#keqpffaeoj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#keqpffaeoj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#keqpffaeoj .gt_from_md > :first-child {
  margin-top: 0;
}

#keqpffaeoj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#keqpffaeoj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#keqpffaeoj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#keqpffaeoj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#keqpffaeoj .gt_row_group_first td {
  border-top-width: 2px;
}

#keqpffaeoj .gt_row_group_first th {
  border-top-width: 2px;
}

#keqpffaeoj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#keqpffaeoj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#keqpffaeoj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#keqpffaeoj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#keqpffaeoj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#keqpffaeoj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#keqpffaeoj .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#keqpffaeoj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#keqpffaeoj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#keqpffaeoj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#keqpffaeoj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#keqpffaeoj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#keqpffaeoj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#keqpffaeoj .gt_left {
  text-align: left;
}

#keqpffaeoj .gt_center {
  text-align: center;
}

#keqpffaeoj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#keqpffaeoj .gt_font_normal {
  font-weight: normal;
}

#keqpffaeoj .gt_font_bold {
  font-weight: bold;
}

#keqpffaeoj .gt_font_italic {
  font-style: italic;
}

#keqpffaeoj .gt_super {
  font-size: 65%;
}

#keqpffaeoj .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#keqpffaeoj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#keqpffaeoj .gt_indent_1 {
  text-indent: 5px;
}

#keqpffaeoj .gt_indent_2 {
  text-indent: 10px;
}

#keqpffaeoj .gt_indent_3 {
  text-indent: 15px;
}

#keqpffaeoj .gt_indent_4 {
  text-indent: 20px;
}

#keqpffaeoj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="6" class="gt_heading gt_title gt_font_normal gt_bottom_border" style="">Traffic Accident Statistics - Continuous Variables</td>
    </tr>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Category">Category</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Drinking_mean">Drinking_mean</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Drinking_sd">Drinking_sd</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Non_Drinking_mean">Non_Drinking_mean</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Non_Drinking_sd">Non_Drinking_sd</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="P_value">P_value</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Category" class="gt_row gt_left">PCTBACHMOR</td>
<td headers="Drinking_mean" class="gt_row gt_right">16.61173</td>
<td headers="Drinking_sd" class="gt_row gt_right">18.72091</td>
<td headers="Non_Drinking_mean" class="gt_row gt_right">16.56986</td>
<td headers="Non_Drinking_sd" class="gt_row gt_right">18.21426</td>
<td headers="P_value" class="gt_row gt_right">0.9137</td></tr>
    <tr><td headers="Category" class="gt_row gt_left">MEDHHINC</td>
<td headers="Drinking_mean" class="gt_row gt_right">31,998.75</td>
<td headers="Drinking_sd" class="gt_row gt_right">17,810.5</td>
<td headers="Non_Drinking_mean" class="gt_row gt_right">31,483.05</td>
<td headers="Non_Drinking_sd" class="gt_row gt_right">16,930.1</td>
<td headers="P_value" class="gt_row gt_right">0.16</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
<p>Among the independent variables, drunk drivers tend to have higher fatality rate, faster car speed, and higher percentage of overturning cars from the primary exploratory analysis.</p>
</section>
<section id="association" class="level3">
<h3 class="anchored" data-anchor-id="association">Association</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="MUSA500_HW3_files/figure-html/Pearson_Cor-1.png" class="img-fluid" width="768"></p>
</div>
</div>
</section>
</section>
<section id="logistic-regression-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-assumptions">Logistic Regression Assumptions</h2>
<section id="pairwise-pearson-correlations-matrix" class="level3">
<h3 class="anchored" data-anchor-id="pairwise-pearson-correlations-matrix">Pairwise Pearson Correlations Matrix</h3>
<p>The correlation matrix in the graph and table is shown below. It is used to test multicollinearity between the predictors. The table shows that the greatest correlation coefficients between predictors are 0.50 and 0.47, which are not strongly correlated. Therefore, no severe multicollinearity between the predictors has been observed.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="MUSA500_HW3_files/figure-html/matrix-1.png" class="img-fluid" width="384"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               FATAL_OR_M    OVERTURNED    CELL_PHONE      SPEEDING  AGGRESSIVE
FATAL_OR_M    1.000000000  0.0331959240  0.0021603225  0.0817126678 -0.01104729
OVERTURNED    0.033195924  1.0000000000 -0.0009897786  0.0594402861  0.01643894
CELL_PHONE    0.002160322 -0.0009897786  1.0000000000 -0.0036011640 -0.02574299
SPEEDING      0.081712668  0.0594402861 -0.0036011640  1.0000000000  0.21152537
AGGRESSIVE   -0.011047295  0.0164389397 -0.0257429929  0.2115253684  1.00000000
DRIVER1617   -0.002808379  0.0037239674  0.0014851333  0.0160115997  0.02842895
DRIVER65PLUS -0.012512349 -0.0195009743 -0.0027172590 -0.0328541108  0.01502693
PCTBACHMOR   -0.014652265  0.0093321352 -0.0012458540 -0.0007390853  0.02712211
MEDHHINC     -0.018212431  0.0279213029  0.0020998852  0.0117866805  0.04344045
               DRIVER1617 DRIVER65PLUS    PCTBACHMOR     MEDHHINC
FATAL_OR_M   -0.002808379 -0.012512349 -0.0146522648 -0.018212431
OVERTURNED    0.003723967 -0.019500974  0.0093321352  0.027921303
CELL_PHONE    0.001485133 -0.002717259 -0.0012458540  0.002099885
SPEEDING      0.016011600 -0.032854111 -0.0007390853  0.011786681
AGGRESSIVE    0.028428953  0.015026930  0.0271221096  0.043440451
DRIVER1617    1.000000000 -0.020848417 -0.0026359662  0.022877425
DRIVER65PLUS -0.020848417  1.000000000  0.0261903901  0.050337711
PCTBACHMOR   -0.002635966  0.026190390  1.0000000000  0.477869537
MEDHHINC      0.022877425  0.050337711  0.4778695368  1.000000000</code></pre>
</div>
</div>
</section>
<section id="assumptions-check" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-check">Assumptions Check</h3>
<p>Logistic regression has several assumptions, for example the dependent variable must be binary, independence of observations, no severe multicollinearity, and large sample size needed (at least 50 observations per predictor). Our dataset confirms the binary nature of our dependent variable, DRINKING_D, which is limited to values of 0 or 1. The absence of geographical data in our dataset leads us to assume independence of observations without spatial autocorrelations. We assessed multicollinearity among predictors using a Pearson correlation matrix. Here, we define the multicollinearity as the situation where two or more predictors are very strongly correlated with each other, with r&gt;0.9 or r&lt;-0.9. From the matrix table, it indicates generally low or no significant correlations between the predictors, with a notable, yet understandable, relationship between MEDHHINC (Median House Income) and PCTBACHMOR (Percentage of individuals having bachelor’s degree), reflecting the typical correlation between higher education and income.</p>
<p>While a correlation matrix effectively displays pairwise correlations between variables, it’s important to note that the Pearson correlation assumes variables are continuous, not categorical. Given that most of our predictors are binary, with only a couple being continuous, neither Pearson nor Spearman correlation is ideal for assessing correlation and multicollinearity in our case. Instead, we can use the T-test to analyze correlations between a binary and a continuous variable, and the Chi-Squared test for correlations between two binary variables.</p>
</section>
</section>
<section id="logistic-regression-results" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-results">Logistic Regression Results</h2>
<section id="logistic-regression-with-all-predictors" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-with-all-predictors">Logistic Regression With All Predictors</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = DRINKING_D ~ FATAL_OR_M + OVERTURNED + CELL_PHONE + 
    SPEEDING + AGGRESSIVE + DRIVER1617 + DRIVER65PLUS + PCTBACHMOR + 
    MEDHHINC, family = "binomial", data = mydata)

Coefficients:
                 Estimate   Std. Error z value             Pr(&gt;|z|)    
(Intercept)  -2.732506616  0.045875659 -59.563 &lt; 0.0000000000000002 ***
FATAL_OR_M    0.814013802  0.083806924   9.713 &lt; 0.0000000000000002 ***
OVERTURNED    0.928921376  0.109166324   8.509 &lt; 0.0000000000000002 ***
CELL_PHONE    0.029550085  0.197777821   0.149               0.8812    
SPEEDING      1.538975665  0.080545894  19.107 &lt; 0.0000000000000002 ***
AGGRESSIVE   -0.596915946  0.047779238 -12.493 &lt; 0.0000000000000002 ***
DRIVER1617   -1.280295964  0.293147168  -4.367 0.000012572447127933 ***
DRIVER65PLUS -0.774664640  0.095858315  -8.081 0.000000000000000641 ***
PCTBACHMOR   -0.000370634  0.001296387  -0.286               0.7750    
MEDHHINC      0.000002804  0.000001341   2.091               0.0365 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 19036  on 43363  degrees of freedom
Residual deviance: 18340  on 43354  degrees of freedom
AIC: 18360

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Based on the regression results, among all studied predictors, except for CELL_PHONE and PCTBACHMOR with a p value greater than 0.05, the rest of them are all significant. The odd ratio provides some insights. The OR of FATAL_OR_M is 2.26 (95% CI, 1.9 – 2.65), suggesting that in crashes where there was a fatality or major injury (FATAL_OR_M = 1), the odds of the crash involving drunk driving are 2.26 times higher compared to crashes where there was no fatality or major injury (FATAL_OR_M = 0).In other words, crashes that result in fatalities or major injuries are more than twice as likely to involve drunk driving as those that do not result in such severe outcomes. The OR of OVERTURNED is 2.53(95% CI, 2.03 – 3.12), suggesting that in involved an overturned vehicle, the odds of the crash involving drunk driving are 2.53 times higher compared to crashes where no vehicle was overturned. The OR of CELL_PHONE is 1.03(95% CI, 0.68 – 1.49), suggesting that in crashes where driver was using cellphones, the odds of the crash involving drunk driving are 1.03 times higher compared to crashes where driver wasn’t using cellphones. The Odds Ratio (OR) associated with SPEEDING is 4.66(95% CI, 3.97 – 5.45). This indicates that in crashes involving speeding cars, the likelihood of drunk driving being a factor is 4.66 times greater than in crashes where speeding is not a factor. This substantial increase highlights the strong association between speeding and the likelihood of drunk driving in accidents. Also, the OR for AGGRESSIVE driving is 0.55(95% CI, 0.5 – 0.6). This suggests that in incidents involving aggressive driving, the probability of drunk driving being involved is only 55% of that in crashes where aggressive driving is not present. The OR of DRIVER1617 is 0.28(95% CI, 0.15 – 0.47), suggesting that in crashes involved at least one driver who was 16 or 17 years old, the odd of the crash involving drunk driving is 0.28 times as much as crashes where no driver was 16 or 17 years old. The OR of DRIVER65PLUS is 0.46(95% CI, 0.38 – 0.55), suggesting that in crashes involved at least one driver who was at least 65 years old, the odd of the crash involving drunk driving is 0.46 times as much as crashes where no driver was at least 65 years old.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)   FATAL_OR_M   OVERTURNED   CELL_PHONE     SPEEDING   AGGRESSIVE 
  0.06505601   2.25694878   2.53177687   1.02999102   4.65981462   0.55050681 
  DRIVER1617 DRIVER65PLUS   PCTBACHMOR     MEDHHINC 
  0.27795502   0.46085831   0.99962944   1.00000280 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     OR      2.5 %     97.5 %
(Intercept)  0.06505601 0.05947628 0.07119524
FATAL_OR_M   2.25694878 1.90991409 2.65313350
OVERTURNED   2.53177687 2.03462326 3.12242730
CELL_PHONE   1.02999102 0.68354737 1.48846840
SPEEDING     4.65981462 3.97413085 5.45020642
AGGRESSIVE   0.55050681 0.50101688 0.60423487
DRIVER1617   0.27795502 0.14774429 0.47109277
DRIVER65PLUS 0.46085831 0.37998364 0.55347851
PCTBACHMOR   0.99962944 0.99707035 1.00215087
MEDHHINC     1.00000280 1.00000013 1.00000539</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate Std. Error     z value   Pr(&gt;|z|)         OR
(Intercept)  -2.73250662 0.04587566 -59.5633209 0.00000000 0.06505601
FATAL_OR_M    0.81401380 0.08380692   9.7129660 0.00000000 2.25694878
OVERTURNED    0.92892138 0.10916632   8.5092302 0.00000000 2.53177687
CELL_PHONE    0.02955008 0.19777782   0.1494105 0.88122972 1.02999102
SPEEDING      1.53897567 0.08054589  19.1068171 0.00000000 4.65981462
AGGRESSIVE   -0.59691595 0.04777924 -12.4932078 0.00000000 0.55050681
DRIVER1617   -1.28029596 0.29314717  -4.3674171 0.00001257 0.27795502
DRIVER65PLUS -0.77466464 0.09585832  -8.0813505 0.00000000 0.46085831
PCTBACHMOR   -0.00037063 0.00129639  -0.2858974 0.77495667 0.99962944
MEDHHINC      0.00000280 0.00000134   2.0913870 0.03649338 1.00000280
                  2.5 %     97.5 %
(Intercept)  0.05947628 0.07119524
FATAL_OR_M   1.90991409 2.65313350
OVERTURNED   2.03462326 3.12242730
CELL_PHONE   0.68354737 1.48846840
SPEEDING     3.97413085 5.45020642
AGGRESSIVE   0.50101688 0.60423487
DRIVER1617   0.14774429 0.47109277
DRIVER65PLUS 0.37998364 0.55347851
PCTBACHMOR   0.99707035 1.00215087
MEDHHINC     1.00000013 1.00000539</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="MUSA500_HW3_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
  fit.binary |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |      2374 |        41 |      2415 | 
             |     0.058 |     0.016 |           | 
-------------|-----------|-----------|-----------|
        TRUE |     38505 |      2444 |     40949 | 
             |     0.942 |     0.984 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
 fit.binary2 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |      2613 |        48 |      2661 | 
             |     0.064 |     0.019 |           | 
-------------|-----------|-----------|-----------|
        TRUE |     38266 |      2437 |     40703 | 
             |     0.936 |     0.981 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
 fit.binary5 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |     19176 |       659 |     19835 | 
             |     0.469 |     0.265 |           | 
-------------|-----------|-----------|-----------|
        TRUE |     21703 |      1826 |     23529 | 
             |     0.531 |     0.735 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
 fit.binary7 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |     37356 |      1935 |     39291 | 
             |     0.914 |     0.779 |           | 
-------------|-----------|-----------|-----------|
        TRUE |      3523 |       550 |      4073 | 
             |     0.086 |     0.221 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
 fit.binary8 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |     38370 |      2026 |     40396 | 
             |     0.939 |     0.815 |           | 
-------------|-----------|-----------|-----------|
        TRUE |      2509 |       459 |      2968 | 
             |     0.061 |     0.185 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
 fit.binary9 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |     38670 |      2067 |     40737 | 
             |     0.946 |     0.832 |           | 
-------------|-----------|-----------|-----------|
        TRUE |      2209 |       418 |      2627 | 
             |     0.054 |     0.168 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
fit.binary10 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |     38762 |      2077 |     40839 | 
             |     0.948 |     0.836 |           | 
-------------|-----------|-----------|-----------|
        TRUE |      2117 |       408 |      2525 | 
             |     0.052 |     0.164 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
fit.binary15 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |     39743 |      2226 |     41969 | 
             |     0.972 |     0.896 |           | 
-------------|-----------|-----------|-----------|
        TRUE |      1136 |       259 |      1395 | 
             |     0.028 |     0.104 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
fit.binary20 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |     40690 |      2428 |     43118 | 
             |     0.995 |     0.977 |           | 
-------------|-----------|-----------|-----------|
        TRUE |       189 |        57 |       246 | 
             |     0.005 |     0.023 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 
   Cell Contents
|-------------------------|
|                       N |
|           N / Col Total |
|-------------------------|

 
Total Observations in Table:  43364 

 
             | mydata$DRINKING_D 
fit.binary50 |         0 |         1 | Row Total | 
-------------|-----------|-----------|-----------|
       FALSE |     40875 |      2481 |     43356 | 
             |     1.000 |     0.998 |           | 
-------------|-----------|-----------|-----------|
        TRUE |         4 |         4 |         8 | 
             |     0.000 |     0.002 |           | 
-------------|-----------|-----------|-----------|
Column Total |     40879 |      2485 |     43364 | 
             |     0.943 |     0.057 |           | 
-------------|-----------|-----------|-----------|

 </code></pre>
</div>
</div>
<p>We also computed the specificity, sensitivity, and misclassification rates for various probability cut-offs. The results, presented in the cutoff value table, reveal that a cutoff value of 0.02 corresponds to the highest misclassification rate at 0.89. In contrast, cutoff values of 0.2 and 0.5 demonstrate the lowest misclassification rates, both standing at 0.06. This implies that at these cutoff points, only 6% of cases were inaccurately classified, either as false positives or false negatives, indicating a higher accuracy in predictive performance.</p>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="cell-output-display">

<div id="madxvfdwyv" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#madxvfdwyv table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#madxvfdwyv thead, #madxvfdwyv tbody, #madxvfdwyv tfoot, #madxvfdwyv tr, #madxvfdwyv td, #madxvfdwyv th {
  border-style: none;
}

#madxvfdwyv p {
  margin: 0;
  padding: 0;
}

#madxvfdwyv .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#madxvfdwyv .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#madxvfdwyv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#madxvfdwyv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#madxvfdwyv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#madxvfdwyv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#madxvfdwyv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#madxvfdwyv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#madxvfdwyv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#madxvfdwyv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#madxvfdwyv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#madxvfdwyv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#madxvfdwyv .gt_spanner_row {
  border-bottom-style: hidden;
}

#madxvfdwyv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#madxvfdwyv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#madxvfdwyv .gt_from_md > :first-child {
  margin-top: 0;
}

#madxvfdwyv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#madxvfdwyv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#madxvfdwyv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#madxvfdwyv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#madxvfdwyv .gt_row_group_first td {
  border-top-width: 2px;
}

#madxvfdwyv .gt_row_group_first th {
  border-top-width: 2px;
}

#madxvfdwyv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#madxvfdwyv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#madxvfdwyv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#madxvfdwyv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#madxvfdwyv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#madxvfdwyv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#madxvfdwyv .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#madxvfdwyv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#madxvfdwyv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#madxvfdwyv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#madxvfdwyv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#madxvfdwyv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#madxvfdwyv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#madxvfdwyv .gt_left {
  text-align: left;
}

#madxvfdwyv .gt_center {
  text-align: center;
}

#madxvfdwyv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#madxvfdwyv .gt_font_normal {
  font-weight: normal;
}

#madxvfdwyv .gt_font_bold {
  font-weight: bold;
}

#madxvfdwyv .gt_font_italic {
  font-style: italic;
}

#madxvfdwyv .gt_super {
  font-size: 65%;
}

#madxvfdwyv .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#madxvfdwyv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#madxvfdwyv .gt_indent_1 {
  text-indent: 5px;
}

#madxvfdwyv .gt_indent_2 {
  text-indent: 10px;
}

#madxvfdwyv .gt_indent_3 {
  text-indent: 15px;
}

#madxvfdwyv .gt_indent_4 {
  text-indent: 20px;
}

#madxvfdwyv .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="4" class="gt_heading gt_title gt_font_normal gt_bottom_border" style="">Cut-off Value Table</td>
    </tr>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Cut_off_Value">Cut_off_Value</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Sensitivity">Sensitivity</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Specificity">Specificity</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Misclassification_Rate">Misclassification_Rate</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.02</td>
<td headers="Sensitivity" class="gt_row gt_right">0.98</td>
<td headers="Specificity" class="gt_row gt_right">0.06</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.89</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.03</td>
<td headers="Sensitivity" class="gt_row gt_right">0.98</td>
<td headers="Specificity" class="gt_row gt_right">0.06</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.88</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.05</td>
<td headers="Sensitivity" class="gt_row gt_right">0.27</td>
<td headers="Specificity" class="gt_row gt_right">0.45</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.52</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.07</td>
<td headers="Sensitivity" class="gt_row gt_right">0.22</td>
<td headers="Specificity" class="gt_row gt_right">0.91</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.13</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.08</td>
<td headers="Sensitivity" class="gt_row gt_right">0.18</td>
<td headers="Specificity" class="gt_row gt_right">0.94</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.1</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.09</td>
<td headers="Sensitivity" class="gt_row gt_right">0.17</td>
<td headers="Specificity" class="gt_row gt_right">0.95</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.1</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.10</td>
<td headers="Sensitivity" class="gt_row gt_right">0.16</td>
<td headers="Specificity" class="gt_row gt_right">0.95</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.1</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.15</td>
<td headers="Sensitivity" class="gt_row gt_right">0.1</td>
<td headers="Specificity" class="gt_row gt_right">0.97</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.1</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.2</td>
<td headers="Sensitivity" class="gt_row gt_right">0.02</td>
<td headers="Specificity" class="gt_row gt_right">1</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.06</td></tr>
    <tr><td headers="Cut_off_Value" class="gt_row gt_right">0.5</td>
<td headers="Sensitivity" class="gt_row gt_right">0</td>
<td headers="Specificity" class="gt_row gt_right">1</td>
<td headers="Misclassification_Rate" class="gt_row gt_right">0.06</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</section>
<section id="roc" class="level3">
<h3 class="anchored" data-anchor-id="roc">ROC</h3>
<p>We also look at the ROC curve to further assess our model. Based on the result, the optimal cut off rate in this scenario, which minimizes both sensitivity and specificity, is 0.06. At this cutoff, the sensitivity is 0.66, meaning the model correctly identifies 66% of alcohol-related crashes. The specificity is 0.55, meaning the model correctly identifies 55% of crashes that are not alcohol related. The result is different from the result shown in the previous section, where the cutoff value 0.2 with the lowest minimum mis-classification rates of 0.06 is considered as the optimal one. The reason is that the former approach focuses more on overall accuracy of the model rather than balancing sensitivity and specificity, while the ROC approach prioritizes a more balanced approach between capturing as many true alcohol-related crashes as possible (sensitivity) and correctly identifying non-alcohol-related crashes (specificity).</p>
<p>Also, the AUC (area under the ROC curve), which is usually interpreted as the probability that the model correctly ranks two randomly selected observations where one has 𝑦=1 and the other one has 𝑦=0, provides some insight. To elaborate, the AUC here is 0.64, meaning that there is a 64% chance that the model will be able to distinguish between a crash that was caused by alcohol and one that was not. This AUC is better than random guessing but shows that there is still considerable room for improvement in the model’s ability to discriminate between positive and negative instances.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  labels predictions
1      0  0.06794568
2      0  0.08305194
3      0  0.06794568
4      0  0.03858293
5      0  0.06794568
6      1  0.07048039</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MUSA500_HW3_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.6398695</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                  [,1]
sensitivity 0.66076459
specificity 0.54524328
cutoff      0.06365151</code></pre>
</div>
</div>
</section>
<section id="logistic-regression-with-binary-predictors-only" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-with-binary-predictors-only">Logistic Regression With Binary Predictors Only</h3>
<p>For comparison, we also run another logistic regression with the binary predictors only (FATAL_OR_M, OVERTURNED, CELL_PHONE, SPEEDING, AGGRESSIVE, DRIVER1617, DRIVER65PLUS). To elaborate, the OR of FATAL_OR_M is 2.25 (95% CI, 1.9 – 2.64), suggesting that in crashes where there was a fatality or major injury (FATAL_OR_M = 1), the odds of the crash involving drunk driving are 2.25 times higher compared to crashes where there was no fatality or major injury (FATAL_OR_M = 0).In other words, crashes that result in fatalities or major injuries are more than twice as likely to involve drunk driving as those that do not result in such severe outcomes. The OR of OVERTURNED is 2.56(95% CI, 2.06 – 3.16), suggesting that in involved an overturned vehicle, the odds of the crash involving drunk driving are 2.56 times higher compared to crashes where no vehicle was overturned. The OR of CELL_PHONE is 1.03(95% CI, 0.68 – 1.49), suggesting that in crashes where driver was using cellphones, the odds of the crash involving drunk driving are 1.03 times higher compared to crashes where driver wasn’t using cellphones. The OR associated with SPEEDING is 4.67(95% CI, 3.98 – 5.46). This indicates that in crashes involving speeding cars, the likelihood of drunk driving being a factor is 4.67 times greater than in crashes where speeding is not a factor. This substantial increase highlights the strong association between speeding and the likelihood of drunk driving in accidents. Also, the OR for AGGRESSIVE driving is 0.55(95% CI, 0.5 – 0.6). This suggests that in incidents involving aggressive driving, the probability of drunk driving being involved is only 55% of that in crashes where aggressive driving is not present. The OR of DRIVER1617 is 0.28(95% CI, 0.15 – 0.48), suggesting that in crashes involved at least one driver who was 16 or 17 years old, the odd of the crash involving drunk driving is 0.28 times as much as crashes where no driver was 16 or 17 years old. The OR of DRIVER65PLUS is 0.46(95% CI, 0.38 – 0.56), suggesting that in crashes involved at least one driver who was at least 65 years old, the odd of the crash involving drunk driving is 0.46 times as much as crashes where no driver was at least 65 years old.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = DRINKING_D ~ FATAL_OR_M + OVERTURNED + CELL_PHONE + 
    SPEEDING + AGGRESSIVE + DRIVER1617 + DRIVER65PLUS, family = "binomial", 
    data = mydata)

Coefficients:
             Estimate Std. Error z value             Pr(&gt;|z|)    
(Intercept)  -2.65190    0.02753 -96.324 &lt; 0.0000000000000002 ***
FATAL_OR_M    0.80932    0.08376   9.662 &lt; 0.0000000000000002 ***
OVERTURNED    0.93978    0.10903   8.619 &lt; 0.0000000000000002 ***
CELL_PHONE    0.03107    0.19777   0.157                0.875    
SPEEDING      1.54032    0.08053  19.128 &lt; 0.0000000000000002 ***
AGGRESSIVE   -0.59365    0.04775 -12.433 &lt; 0.0000000000000002 ***
DRIVER1617   -1.27158    0.29311  -4.338  0.00001436374143265 ***
DRIVER65PLUS -0.76646    0.09576  -8.004  0.00000000000000121 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 19036  on 43363  degrees of freedom
Residual deviance: 18344  on 43356  degrees of freedom
AIC: 18360

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)   FATAL_OR_M   OVERTURNED   CELL_PHONE     SPEEDING   AGGRESSIVE 
  0.07051713   2.24636998   2.55942903   1.03156149   4.66608472   0.55230941 
  DRIVER1617 DRIVER65PLUS 
  0.28038936   0.46465631 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    OR2      2.5 %    97.5 %
(Intercept)  0.07051713 0.06678642 0.0743978
FATAL_OR_M   2.24636998 1.90112455 2.6404533
OVERTURNED   2.55942903 2.05736015 3.1556897
CELL_PHONE   1.03156149 0.68459779 1.4907150
SPEEDING     4.66608472 3.97961862 5.4573472
AGGRESSIVE   0.55230941 0.50268818 0.6061758
DRIVER1617   0.28038936 0.14904734 0.4751771
DRIVER65PLUS 0.46465631 0.38318289 0.5579332</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                Estimate Std. Error     z value   Pr(&gt;|z|)        OR2
(Intercept)  -2.65189961 0.02753107 -96.3238683 0.00000000 0.07051713
FATAL_OR_M    0.80931557 0.08376150   9.6621431 0.00000000 2.24636998
OVERTURNED    0.93978420 0.10903433   8.6191585 0.00000000 2.55942903
CELL_PHONE    0.03107367 0.19777088   0.1571195 0.87515064 1.03156149
SPEEDING      1.54032033 0.08052787  19.1277908 0.00000000 4.66608472
AGGRESSIVE   -0.59364687 0.04774781 -12.4329656 0.00000000 0.55230941
DRIVER1617   -1.27157607 0.29310969  -4.3382260 0.00001436 0.28038936
DRIVER65PLUS -0.76645727 0.09576440  -8.0035718 0.00000000 0.46465631
                  2.5 %    97.5 %
(Intercept)  0.06678642 0.0743978
FATAL_OR_M   1.90112455 2.6404533
OVERTURNED   2.05736015 3.1556897
CELL_PHONE   0.68459779 1.4907150
SPEEDING     3.97961862 5.4573472
AGGRESSIVE   0.50268818 0.6061758
DRIVER1617   0.14904734 0.4751771
DRIVER65PLUS 0.38318289 0.5579332</code></pre>
</div>
</div>
<p>As is shown in the result table, similar with the original model all the perdictors, except for the CELL_PHONE, are significant. Also, when looking at the AIC, the AIC for the original model is 18359.6, while the AIC for the new model is 18360.5, suggesting that the original model is a better model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         df      AIC
mylogit  10 18359.63
mylogit2  8 18360.47</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="summarizing-findings" class="level2">
<h2 class="anchored" data-anchor-id="summarizing-findings">Summarizing findings</h2>
<p>In our study, we analyzed a dataset of 43,364 car crash observations to identify factors associated with crashes involving drunk driving. The dependent variable was ‘DRINKING_D’ (Drinking driver indicator), and various predictors like crash severity, vehicle overturning, cell phone usage, speeding, aggressive driving, age of drivers, and socioeconomic factors including median house income and percentage of individuals getting bachelor’s degree or higher were examined.</p>
<p>Based on the logistic regression result, factors such as crash severity (‘FATAL_OR_M’), vehicle overturning (‘OVERTURNED’), speeding (‘SPEEDING’), age groups of drivers (‘DRIVER1617’ and ‘DRIVER65PLUS’), and median house income (‘MEDHHINC’) significantly predicted drunk driving incidents, although the ‘MEDHHINC’ is not that significant which has a p-value of 0.036 and beta coefficient of 0.0000028. On the contrary, cell phone usage (‘CELL_PHONE’) and education level (‘PCTBACHMOR’) were not significantly associated with the drunk driver crashes. Overall, the findings align closely with our initial expectations. Most variables exhibited behavior that was anticipated, particularly the strong associations observed between speeding and vehicle overturning with instances of drunk driving. It is also reasonable that the cell phone usage, socioeconomic factor median house income and education level do not necessarily have a significant impact on the likelihood of drunk driving incidents. However, it is a bit surprising that aggressive driving, are associated with ORs less than 1, which is suggesting a lower likelihood of drunk driving but is not following our initial expectation.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Counts:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
40879  2485 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Percentages:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
       0        1 
94.26944  5.73056 </code></pre>
</div>
</div>
<p>Our dependent variable DRINKING_D has the appropriate count of each category, having 43364 sample size with 2485 events where DRINKING_D equals 1 occurring, which account for 5.73% of the total. From what Paul Allison proposed, it could be problematic when the sample size is small and there is rarity of the events, which does not really apply in our case. Consequently, the application of logistic regression in our study is appropriate, given the substantial sample size and the proportion of events within it.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>One limitation of the model may be failing to include all possible confounding variables that could influence the likelihood of drunk driving accidents. For instance, factors like road conditions, weather, or specific traffic patterns, which might have a significant impact, are not considered. In addition, in reality the traffic crash data will have some extent of spatial autocorrelation as certain areas might have higher accident rates due to specific local conditions. However, in our case we did not take those into considerations.</p>
<p>The primary limitation of our analysis is reflected in the Area Under the Curve (AUC) of the Receiver Operating Characteristic (ROC) curve, a crucial metric for assessing the model’s predictive accuracy. In our model, the AUC is approximately 0.64, which, according to standard guidelines, is categorized as poor (grade D). This rating indicates a relatively low effectiveness of the model in distinguishing between the binary outcomes, specifically in correctly predicting ‘1’ responses as ‘1s’ and ‘0’ responses as ‘0s’.</p>
</section>
</section>
<section id="reference" class="level1">
<h1>Reference</h1>
<p>National Highway Traffic Safety Administration. (2020). Drunk Driving. U.S.Department of Transportation. https://www.nhtsa.gov/risky-driving/drunk-driving#:~:text=About%2031%25%20of%20all%20traffic,killed%20in%20these%20preventable%20crashes</p>
<p>City of Philadelphia. (2023). City of Philadelphia Releases Vision Zero Annual Report 2023. https://www.phila.gov/2023-10-10-city-of-philadelphia-releases-vision-zero-annual-report-2023/</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© CC-Hang Zhao, 2023</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This page is built with ❤️ and <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>