project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Hang Zhao Personal Website"
  site-url: "https://cyanhang.github.io/Hang/" 
  repo-url: https://github.com/Cyanhang/Hang 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Hang Zhao, 2023"

  sidebar:
    logo: "images/Penn_Logo.jpg"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: hangzh@sas.upenn.edu
        text: "Email"
      - icon: github
        href: https://github.com/Cyanhang
        text: "Hang's GitHub"
      - icon: linkedin
        href: www.linkedin.com/in/hang-zhao-62060a1a9
        text: "Hang's Linkedin"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: MUSA550_Python
        contents:
          - MUSA550_Python/MUSA550_Assignment2_HangZhao.ipynb
          - MUSA550_Python/assignment-3-HangZhao.ipynb
          - MUSA550_Python/assignment-4.ipynb
          - MUSA550_Python/assignment-5.ipynb
          - MUSA550_Python/assignment-6.ipynb
      - section: MUSA500_Stats
        contents:
          - MUSA500_Stats/MUSA500_HW1_PredictHouseValues.Rmd
          - MUSA500_Stats/MUSA500_HW2.Rmd
          - MUSA500_Stats/MUSA500_HW3.Rmd
      - ENVS_PuertoRico/index.qmd
     

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




